ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS dispute_opened_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dispute_opened_by BIGINT REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS dispute_client_agree BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS dispute_editor_agree BOOLEAN NOT NULL DEFAULT FALSE;
